package micdoodle8.mods.crossbowmod;

import cpw.mods.fml.common.registry.LanguageRegistry;
import net.minecraft.src.Block;
import net.minecraft.src.Item;

public class Items 
{
	public static Block crossbowBench;
	
	public static ItemWoodCrossbow woodenCrossbowBase;
	public static ItemWoodCrossbow woodenCrossbowWithBasicScope;
	public static ItemWoodCrossbow woodenCrossbowWithLongScope;
	public static ItemWoodCrossbow woodenCrossbowWithBasicScopeAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithLongScopeAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithBasicScopeAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithLongScopeAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithBasicScopeAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithLongScopeAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithExplosiveAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithExplosiveAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithExplosiveAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithExplosiveAttachmentAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithFlameAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithFlameAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithFlameAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithFlameAttachmentAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithLavaAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithLavaAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithLavaAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithLavaAttachmentAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithIceAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithIceAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithIceAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithIceAttachmentAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithLightningAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithLightningAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithLightningAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithLightningAttachmentAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithTorchAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithTorchAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithTorchAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithTorchAttachmentAndHeavyMech;
	public static ItemWoodCrossbow woodenCrossbowWithPoisonAttachment;
	public static ItemWoodCrossbow woodenCrossbowWithPoisonAttachmentAndLightMech;
	public static ItemWoodCrossbow woodenCrossbowWithPoisonAttachmentAndMediumMech;
	public static ItemWoodCrossbow woodenCrossbowWithPoisonAttachmentAndHeavyMech;

	public static ItemStoneCrossbow stoneCrossbowBase;
	public static ItemStoneCrossbow stoneCrossbowWithBasicScope;
	public static ItemStoneCrossbow stoneCrossbowWithLongScope;
	public static ItemStoneCrossbow stoneCrossbowWithBasicScopeAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithLongScopeAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithBasicScopeAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithLongScopeAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithBasicScopeAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithLongScopeAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithExplosiveAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithExplosiveAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithExplosiveAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithExplosiveAttachmentAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithFlameAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithFlameAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithFlameAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithFlameAttachmentAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithLavaAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithLavaAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithLavaAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithLavaAttachmentAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithIceAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithIceAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithIceAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithIceAttachmentAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithLightningAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithLightningAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithLightningAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithLightningAttachmentAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithTorchAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithTorchAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithTorchAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithTorchAttachmentAndHeavyMech;
	public static ItemStoneCrossbow stoneCrossbowWithPoisonAttachment;
	public static ItemStoneCrossbow stoneCrossbowWithPoisonAttachmentAndLightMech;
	public static ItemStoneCrossbow stoneCrossbowWithPoisonAttachmentAndMediumMech;
	public static ItemStoneCrossbow stoneCrossbowWithPoisonAttachmentAndHeavyMech;

	public static ItemIronCrossbow ironCrossbowBase;
	public static ItemIronCrossbow ironCrossbowWithBasicScope;
	public static ItemIronCrossbow ironCrossbowWithLongScope;
	public static ItemIronCrossbow ironCrossbowWithBasicScopeAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithLongScopeAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithBasicScopeAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithLongScopeAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithBasicScopeAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithLongScopeAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithLightMech;
	public static ItemIronCrossbow ironCrossbowWithMediumMech;
	public static ItemIronCrossbow ironCrossbowWithHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithExplosiveAttachment;
	public static ItemIronCrossbow ironCrossbowWithExplosiveAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithExplosiveAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithExplosiveAttachmentAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithFlameAttachment;
	public static ItemIronCrossbow ironCrossbowWithFlameAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithFlameAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithFlameAttachmentAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithLavaAttachment;
	public static ItemIronCrossbow ironCrossbowWithLavaAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithLavaAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithLavaAttachmentAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithIceAttachment;
	public static ItemIronCrossbow ironCrossbowWithIceAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithIceAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithIceAttachmentAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithLightningAttachment;
	public static ItemIronCrossbow ironCrossbowWithLightningAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithLightningAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithLightningAttachmentAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithTorchAttachment;
	public static ItemIronCrossbow ironCrossbowWithTorchAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithTorchAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithTorchAttachmentAndHeavyMech;
	public static ItemIronCrossbow ironCrossbowWithPoisonAttachment;
	public static ItemIronCrossbow ironCrossbowWithPoisonAttachmentAndLightMech;
	public static ItemIronCrossbow ironCrossbowWithPoisonAttachmentAndMediumMech;
	public static ItemIronCrossbow ironCrossbowWithPoisonAttachmentAndHeavyMech;

	public static ItemGoldCrossbow goldCrossbowBase;
	public static ItemGoldCrossbow goldCrossbowWithBasicScope;
	public static ItemGoldCrossbow goldCrossbowWithLongScope;
	public static ItemGoldCrossbow goldCrossbowWithBasicScopeAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithLongScopeAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithBasicScopeAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithLongScopeAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithBasicScopeAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithLongScopeAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithLightMech;
	public static ItemGoldCrossbow goldCrossbowWithMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithExplosiveAttachment;
	public static ItemGoldCrossbow goldCrossbowWithExplosiveAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithExplosiveAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithExplosiveAttachmentAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithFlameAttachment;
	public static ItemGoldCrossbow goldCrossbowWithFlameAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithFlameAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithFlameAttachmentAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithLavaAttachment;
	public static ItemGoldCrossbow goldCrossbowWithLavaAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithLavaAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithLavaAttachmentAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithIceAttachment;
	public static ItemGoldCrossbow goldCrossbowWithIceAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithIceAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithIceAttachmentAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithLightningAttachment;
	public static ItemGoldCrossbow goldCrossbowWithLightningAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithLightningAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithLightningAttachmentAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithTorchAttachment;
	public static ItemGoldCrossbow goldCrossbowWithTorchAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithTorchAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithTorchAttachmentAndHeavyMech;
	public static ItemGoldCrossbow goldCrossbowWithPoisonAttachment;
	public static ItemGoldCrossbow goldCrossbowWithPoisonAttachmentAndLightMech;
	public static ItemGoldCrossbow goldCrossbowWithPoisonAttachmentAndMediumMech;
	public static ItemGoldCrossbow goldCrossbowWithPoisonAttachmentAndHeavyMech;

	public static ItemDiamondCrossbow diamondCrossbowBase;
	public static ItemDiamondCrossbow diamondCrossbowWithBasicScope;
	public static ItemDiamondCrossbow diamondCrossbowWithLongScope;
	public static ItemDiamondCrossbow diamondCrossbowWithBasicScopeAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLongScopeAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithBasicScopeAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLongScopeAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithBasicScopeAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLongScopeAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithExplosiveAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithExplosiveAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithExplosiveAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithExplosiveAttachmentAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithFlameAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithFlameAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithFlameAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithFlameAttachmentAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLavaAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithLavaAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLavaAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLavaAttachmentAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithIceAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithIceAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithIceAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithIceAttachmentAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLightningAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithLightningAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLightningAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithLightningAttachmentAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithTorchAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithTorchAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithTorchAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithTorchAttachmentAndHeavyMech;
	public static ItemDiamondCrossbow diamondCrossbowWithPoisonAttachment;
	public static ItemDiamondCrossbow diamondCrossbowWithPoisonAttachmentAndLightMech;
	public static ItemDiamondCrossbow diamondCrossbowWithPoisonAttachmentAndMediumMech;
	public static ItemDiamondCrossbow diamondCrossbowWithPoisonAttachmentAndHeavyMech;
	
	public static ItemCBMod woodBolt;
	public static ItemCBMod stoneBolt;
	public static ItemCBMod ironBolt;
	public static ItemCBMod goldBolt;
	public static ItemCBMod diamondBolt;
	
	public static ItemCBMod woodLimb;
	public static ItemCBMod stoneLimb;
	public static ItemCBMod ironLimb;
	public static ItemCBMod goldLimb;
	public static ItemCBMod diamondLimb;

	public static ItemCBMod mechanismSemiAuto;
	public static ItemCBMod mechanismLightAuto;
	public static ItemCBMod mechanismMediumAuto;
	public static ItemCBMod mechanismHeavyAuto;
	
	public static ItemCBMod attachmentShortScope;
	public static ItemCBMod attachmentLongScope;
	public static ItemCBMod attachmentFire;
	public static ItemCBMod attachmentLava;
	public static ItemCBMod attachmentExplosive;
	public static ItemCBMod attachmentIce;
	public static ItemCBMod attachmentLightning;
	public static ItemCBMod attachmentTorch;
	public static ItemCBMod attachmentPoison;
	
	public Items()
	{
		crossbowBench = new BlockCrossbowBench(ConfigManager.idBlockCrossbowBench).setHardness(2.5F).setStepSound(Block.soundWoodFootstep).setBlockName("blockBlockCrossbowBench");

	    woodenCrossbowBase = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowBase - 256).setIconIndex(0).setItemName("woodenCrossbow").setMaxStackSize(1);
		woodenCrossbowWithBasicScope = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithBasicScope - 256).setIconIndex(1).setItemName("woodenCrossbowWithBasicScope").setMaxStackSize(1);
		woodenCrossbowWithLongScope = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLongScope - 256).setIconIndex(2).setItemName("woodenCrossbowWithLongScope").setMaxStackSize(1);
		woodenCrossbowWithBasicScopeAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithBasicScopeAndLightMech - 256).setIconIndex(3).setItemName("woodenCrossbowWithBasicScopeAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithLongScopeAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLongScopeAndLightMech - 256).setIconIndex(4).setItemName("woodenCrossbowWithLongScopeAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithBasicScopeAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithBasicScopeAndMediumMech - 256).setIconIndex(5).setItemName("woodenCrossbowWithBasicScopeAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithLongScopeAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLongScopeAndMediumMech - 256).setIconIndex(6).setItemName("woodenCrossbowWithLongScopeAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithBasicScopeAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithBasicScopeAndHeavyMech - 256).setIconIndex(7).setItemName("woodenCrossbowWithBasicScopeAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithLongScopeAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLongScopeAndHeavyMech - 256).setIconIndex(8).setItemName("woodenCrossbowWithLongScopeAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLightMech - 256).setIconIndex(9).setItemName("woodenCrossbowWithLightMech").setMaxStackSize(1);
		woodenCrossbowWithMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithMediumMech - 256).setIconIndex(10).setItemName("woodenCrossbowWithMediumMech").setMaxStackSize(1);
		woodenCrossbowWithHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithHeavyMech - 256).setIconIndex(11).setItemName("woodenCrossbowWithHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithExplosiveAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithExplosiveAttachment - 256).setIconIndex(12).setItemName("woodenCrossbowWithExplosiveAttachment").setMaxStackSize(1);
		woodenCrossbowWithExplosiveAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithExplosiveAttachmentAndLightMech - 256).setIconIndex(13).setItemName("woodenCrossbowWithExplosiveAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithExplosiveAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithExplosiveAttachmentAndMediumMech - 256).setIconIndex(14).setItemName("woodenCrossbowWithExplosiveAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithExplosiveAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithExplosiveAttachmentAndHeavyMech - 256).setIconIndex(15).setItemName("woodenCrossbowWithExplosiveAttachmentAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithFlameAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithFireAttachment - 256).setIconIndex(0 + 32 + 16).setItemName("woodenCrossbowWithFireAttachment").setMaxStackSize(1);
		woodenCrossbowWithFlameAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithFireAttachmentAndLightMech - 256).setIconIndex(1 + 32 + 16).setItemName("woodenCrossbowWithFireAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithFlameAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithFireAttachmentAndMediumMech - 256).setIconIndex(2 + 32 + 16).setItemName("woodenCrossbowWithFireAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithFlameAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithFireAttachmentAndHeavyMech - 256).setIconIndex(3 + 32 + 16).setItemName("woodenCrossbowWithFireAttachmentAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithLavaAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLavaAttachment - 256).setIconIndex(4 + 32 + 16).setItemName("woodenCrossbowWithLavaAttachment").setMaxStackSize(1);
		woodenCrossbowWithLavaAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLavaAttachmentAndLightMech - 256).setIconIndex(5 + 32 + 16).setItemName("woodenCrossbowWithLavaAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithLavaAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLavaAttachmentAndMediumMech - 256).setIconIndex(6 + 32 + 16).setItemName("woodenCrossbowWithLavaAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithLavaAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLavaAttachmentAndHeavyMech - 256).setIconIndex(7 + 32 + 16).setItemName("woodenCrossbowWithLavaAttachmentAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithIceAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithIceAttachment - 256).setIconIndex(8 + 32 + 16).setItemName("woodenCrossbowWithIceAttachment").setMaxStackSize(1);
		woodenCrossbowWithIceAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithIceAttachmentAndLightMech - 256).setIconIndex(9 + 32 + 16).setItemName("woodenCrossbowWithIceAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithIceAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithIceAttachmentAndMediumMech - 256).setIconIndex(10 + 32 + 16).setItemName("woodenCrossbowWithIceAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithIceAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithIceAttachmentAndHeavyMech - 256).setIconIndex(11 + 32 + 16).setItemName("woodenCrossbowWithIceAttachmentAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithLightningAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLightningAttachment - 256).setIconIndex(12 + 32 + 16).setItemName("woodenCrossbowWithLightningAttachment").setMaxStackSize(1);
		woodenCrossbowWithLightningAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLightningAttachmentAndLightMech - 256).setIconIndex(13 + 32 + 16).setItemName("woodenCrossbowWithLightningAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithLightningAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLightningAttachmentAndMediumMech - 256).setIconIndex(14 + 32 + 16).setItemName("woodenCrossbowWithLightningAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithLightningAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithLightningAttachmentAndHeavyMech - 256).setIconIndex(15 + 32 + 16).setItemName("woodenCrossbowWithLightningAttachmentAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithTorchAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithTorchAttachment - 256).setIconIndex(0 + 64 + 32).setItemName("woodenCrossbowWithTorchAttachment").setMaxStackSize(1);
		woodenCrossbowWithTorchAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithTorchAttachmentAndLightMech - 256).setIconIndex(1 + 64 + 32).setItemName("woodenCrossbowWithTorchAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithTorchAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithTorchAttachmentAndMediumMech - 256).setIconIndex(2 + 64 + 32).setItemName("woodenCrossbowWithTorchAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithTorchAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithTorchAttachmentAndHeavyMech - 256).setIconIndex(3 + 64 + 32).setItemName("woodenCrossbowWithTorchAttachmentAndHeavyMech").setMaxStackSize(1);
		woodenCrossbowWithPoisonAttachment = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithPoisonAttachment - 256).setIconIndex(4 + 64 + 32).setItemName("woodenCrossbowWithPoisonAttachment").setMaxStackSize(1);
		woodenCrossbowWithPoisonAttachmentAndLightMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithPoisonAttachmentAndLightMech - 256).setIconIndex(5 + 64 + 32).setItemName("woodenCrossbowWithPoisonAttachmentAndLightMech").setMaxStackSize(1);
		woodenCrossbowWithPoisonAttachmentAndMediumMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithPoisonAttachmentAndMediumMech - 256).setIconIndex(6 + 64 + 32).setItemName("woodenCrossbowWithPoisonAttachmentAndMediumMech").setMaxStackSize(1);
		woodenCrossbowWithPoisonAttachmentAndHeavyMech = (ItemWoodCrossbow) new ItemWoodCrossbow(ConfigManager.idItemWoodCrossbowWithPoisonAttachmentAndHeavyMech - 256).setIconIndex(7 + 64 + 32).setItemName("woodenCrossbowWithPoisonAttachmentAndHeavyMech").setMaxStackSize(1);
		
		stoneCrossbowBase = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowBase - 256).setIconIndex(0).setItemName("stoneCrossbow").setMaxStackSize(1);
		stoneCrossbowWithBasicScope = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithBasicScope - 256).setIconIndex(1).setItemName("stoneCrossbowWithBasicScope").setMaxStackSize(1);
		stoneCrossbowWithLongScope = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLongScope - 256).setIconIndex(2).setItemName("stoneCrossbowWithLongScope").setMaxStackSize(1);
		stoneCrossbowWithBasicScopeAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithBasicScopeAndLightMech - 256).setIconIndex(3).setItemName("stoneCrossbowWithBasicScopeAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithLongScopeAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLongScopeAndLightMech - 256).setIconIndex(4).setItemName("stoneCrossbowWithLongScopeAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithBasicScopeAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithBasicScopeAndMediumMech - 256).setIconIndex(5).setItemName("stoneCrossbowWithBasicScopeAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithLongScopeAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLongScopeAndMediumMech - 256).setIconIndex(6).setItemName("stoneCrossbowWithLongScopeAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithBasicScopeAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithBasicScopeAndHeavyMech - 256).setIconIndex(7).setItemName("stoneCrossbowWithBasicScopeAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithLongScopeAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLongScopeAndHeavyMech - 256).setIconIndex(8).setItemName("stoneCrossbowWithLongScopeAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLightMech - 256).setIconIndex(9).setItemName("stoneCrossbowWithLightMech").setMaxStackSize(1);
		stoneCrossbowWithMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithMediumMech - 256).setIconIndex(10).setItemName("stoneCrossbowWithMediumMech").setMaxStackSize(1);
		stoneCrossbowWithHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithHeavyMech - 256).setIconIndex(11).setItemName("stoneCrossbowWithHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithExplosiveAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithExplosiveAttachment - 256).setIconIndex(12).setItemName("stoneCrossbowWithExplosiveAttachment").setMaxStackSize(1);
		stoneCrossbowWithExplosiveAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithExplosiveAttachmentAndLightMech - 256).setIconIndex(13).setItemName("stoneCrossbowWithExplosiveAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithExplosiveAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithExplosiveAttachmentAndMediumMech - 256).setIconIndex(14).setItemName("stoneCrossbowWithExplosiveAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithExplosiveAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithExplosiveAttachmentAndHeavyMech - 256).setIconIndex(15).setItemName("stoneCrossbowWithExplosiveAttachmentAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithFlameAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithFireAttachment - 256).setIconIndex(0 + 32 + 16).setItemName("stoneCrossbowWithFireAttachment").setMaxStackSize(1);
		stoneCrossbowWithFlameAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithFireAttachmentAndLightMech - 256).setIconIndex(1 + 32 + 16).setItemName("stoneCrossbowWithFireAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithFlameAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithFireAttachmentAndMediumMech - 256).setIconIndex(2 + 32 + 16).setItemName("stoneCrossbowWithFireAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithFlameAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithFireAttachmentAndHeavyMech - 256).setIconIndex(3 + 32 + 16).setItemName("stoneCrossbowWithFireAttachmentAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithLavaAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLavaAttachment - 256).setIconIndex(4 + 32 + 16).setItemName("stoneCrossbowWithLavaAttachment").setMaxStackSize(1);
		stoneCrossbowWithLavaAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLavaAttachmentAndLightMech - 256).setIconIndex(5 + 32 + 16).setItemName("stoneCrossbowWithLavaAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithLavaAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLavaAttachmentAndMediumMech - 256).setIconIndex(6 + 32 + 16).setItemName("stoneCrossbowWithLavaAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithLavaAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLavaAttachmentAndHeavyMech - 256).setIconIndex(7 + 32 + 16).setItemName("stoneCrossbowWithLavaAttachmentAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithIceAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithIceAttachment - 256).setIconIndex(8 + 32 + 16).setItemName("stoneCrossbowWithIceAttachment").setMaxStackSize(1);
		stoneCrossbowWithIceAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithIceAttachmentAndLightMech - 256).setIconIndex(9 + 32 + 16).setItemName("stoneCrossbowWithIceAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithIceAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithIceAttachmentAndMediumMech - 256).setIconIndex(10 + 32 + 16).setItemName("stoneCrossbowWithIceAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithIceAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithIceAttachmentAndHeavyMech - 256).setIconIndex(11 + 32 + 16).setItemName("stoneCrossbowWithIceAttachmentAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithLightningAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLightningAttachment - 256).setIconIndex(12 + 32 + 16).setItemName("stoneCrossbowWithLightningAttachment").setMaxStackSize(1);
		stoneCrossbowWithLightningAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLightningAttachmentAndLightMech - 256).setIconIndex(13 + 32 + 16).setItemName("stoneCrossbowWithLightningAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithLightningAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLightningAttachmentAndMediumMech - 256).setIconIndex(14 + 32 + 16).setItemName("stoneCrossbowWithLightningAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithLightningAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithLightningAttachmentAndHeavyMech - 256).setIconIndex(15 + 32 + 16).setItemName("stoneCrossbowWithLightningAttachmentAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithTorchAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithTorchAttachment - 256).setIconIndex(0 + 64 + 32).setItemName("stoneCrossbowWithTorchAttachment").setMaxStackSize(1);
		stoneCrossbowWithTorchAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithTorchAttachmentAndLightMech - 256).setIconIndex(1 + 64 + 32).setItemName("stoneCrossbowWithTorchAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithTorchAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithTorchAttachmentAndMediumMech - 256).setIconIndex(2 + 64 + 32).setItemName("stoneCrossbowWithTorchAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithTorchAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithTorchAttachmentAndHeavyMech - 256).setIconIndex(3 + 64 + 32).setItemName("stoneCrossbowWithTorchAttachmentAndHeavyMech").setMaxStackSize(1);
		stoneCrossbowWithPoisonAttachment = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithPoisonAttachment - 256).setIconIndex(4 + 64 + 32).setItemName("stoneCrossbowWithPoisonAttachment").setMaxStackSize(1);
		stoneCrossbowWithPoisonAttachmentAndLightMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithPoisonAttachmentAndLightMech - 256).setIconIndex(5 + 64 + 32).setItemName("stoneCrossbowWithPoisonAttachmentAndLightMech").setMaxStackSize(1);
		stoneCrossbowWithPoisonAttachmentAndMediumMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithPoisonAttachmentAndMediumMech - 256).setIconIndex(6 + 64 + 32).setItemName("stoneCrossbowWithPoisonAttachmentAndMediumMech").setMaxStackSize(1);
		stoneCrossbowWithPoisonAttachmentAndHeavyMech = (ItemStoneCrossbow) new ItemStoneCrossbow(ConfigManager.idItemStoneCrossbowWithPoisonAttachmentAndHeavyMech - 256).setIconIndex(7 + 64 + 32).setItemName("stoneCrossbowWithPoisonAttachmentAndHeavyMech").setMaxStackSize(1);
		
		ironCrossbowBase = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowBase - 256).setIconIndex(0).setItemName("ironCrossbow").setMaxStackSize(1);
		ironCrossbowWithBasicScope = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithBasicScope - 256).setIconIndex(1).setItemName("ironCrossbowWithBasicScope").setMaxStackSize(1);
		ironCrossbowWithLongScope = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLongScope - 256).setIconIndex(2).setItemName("ironCrossbowWithLongScope").setMaxStackSize(1);
		ironCrossbowWithBasicScopeAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithBasicScopeAndLightMech - 256).setIconIndex(3).setItemName("ironCrossbowWithBasicScopeAndLightMech").setMaxStackSize(1);
		ironCrossbowWithLongScopeAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLongScopeAndLightMech - 256).setIconIndex(4).setItemName("ironCrossbowWithLongScopeAndLightMech").setMaxStackSize(1);
		ironCrossbowWithBasicScopeAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithBasicScopeAndMediumMech - 256).setIconIndex(5).setItemName("ironCrossbowWithBasicScopeAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithLongScopeAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLongScopeAndMediumMech - 256).setIconIndex(6).setItemName("ironCrossbowWithLongScopeAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithBasicScopeAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithBasicScopeAndHeavyMech - 256).setIconIndex(7).setItemName("ironCrossbowWithBasicScopeAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithLongScopeAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLongScopeAndHeavyMech - 256).setIconIndex(8).setItemName("ironCrossbowWithLongScopeAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLightMech - 256).setIconIndex(9).setItemName("ironCrossbowWithLightMech").setMaxStackSize(1);
		ironCrossbowWithMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithMediumMech - 256).setIconIndex(10).setItemName("ironCrossbowWithMediumMech").setMaxStackSize(1);
		ironCrossbowWithHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithHeavyMech - 256).setIconIndex(11).setItemName("ironCrossbowWithHeavyMech").setMaxStackSize(1);
		ironCrossbowWithExplosiveAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithExplosiveAttachment - 256).setIconIndex(12).setItemName("ironCrossbowWithExplosiveAttachment").setMaxStackSize(1);
		ironCrossbowWithExplosiveAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithExplosiveAttachmentAndLightMech - 256).setIconIndex(13).setItemName("ironCrossbowWithExplosiveAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithExplosiveAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithExplosiveAttachmentAndMediumMech - 256).setIconIndex(14).setItemName("ironCrossbowWithExplosiveAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithExplosiveAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithExplosiveAttachmentAndHeavyMech - 256).setIconIndex(15).setItemName("ironCrossbowWithExplosiveAttachmentAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithFlameAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithFireAttachment - 256).setIconIndex(0 + 32 + 16).setItemName("ironCrossbowWithFireAttachment").setMaxStackSize(1);
		ironCrossbowWithFlameAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithFireAttachmentAndLightMech - 256).setIconIndex(1 + 32 + 16).setItemName("ironCrossbowWithFireAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithFlameAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithFireAttachmentAndMediumMech - 256).setIconIndex(2 + 32 + 16).setItemName("ironCrossbowWithFireAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithFlameAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithFireAttachmentAndHeavyMech - 256).setIconIndex(3 + 32 + 16).setItemName("ironCrossbowWithFireAttachmentAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithLavaAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLavaAttachment - 256).setIconIndex(4 + 32 + 16).setItemName("ironCrossbowWithLavaAttachment").setMaxStackSize(1);
		ironCrossbowWithLavaAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLavaAttachmentAndLightMech - 256).setIconIndex(5 + 32 + 16).setItemName("ironCrossbowWithLavaAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithLavaAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLavaAttachmentAndMediumMech - 256).setIconIndex(6 + 32 + 16).setItemName("ironCrossbowWithLavaAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithLavaAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLavaAttachmentAndHeavyMech - 256).setIconIndex(7 + 32 + 16).setItemName("ironCrossbowWithLavaAttachmentAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithIceAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithIceAttachment - 256).setIconIndex(8 + 32 + 16).setItemName("ironCrossbowWithIceAttachment").setMaxStackSize(1);
		ironCrossbowWithIceAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithIceAttachmentAndLightMech - 256).setIconIndex(9 + 32 + 16).setItemName("ironCrossbowWithIceAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithIceAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithIceAttachmentAndMediumMech - 256).setIconIndex(10 + 32 + 16).setItemName("ironCrossbowWithIceAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithIceAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithIceAttachmentAndHeavyMech - 256).setIconIndex(11 + 32 + 16).setItemName("ironCrossbowWithIceAttachmentAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithLightningAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLightningAttachment - 256).setIconIndex(12 + 32 + 16).setItemName("ironCrossbowWithLightningAttachment").setMaxStackSize(1);
		ironCrossbowWithLightningAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLightningAttachmentAndLightMech - 256).setIconIndex(13 + 32 + 16).setItemName("ironCrossbowWithLightningAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithLightningAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLightningAttachmentAndMediumMech - 256).setIconIndex(14 + 32 + 16).setItemName("ironCrossbowWithLightningAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithLightningAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithLightningAttachmentAndHeavyMech - 256).setIconIndex(15 + 32 + 16).setItemName("ironCrossbowWithLightningAttachmentAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithTorchAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithTorchAttachment - 256).setIconIndex(0 + 64 + 32).setItemName("ironCrossbowWithTorchAttachment").setMaxStackSize(1);
		ironCrossbowWithTorchAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithTorchAttachmentAndLightMech - 256).setIconIndex(1 + 64 + 32).setItemName("ironCrossbowWithTorchAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithTorchAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithTorchAttachmentAndMediumMech - 256).setIconIndex(2 + 64 + 32).setItemName("ironCrossbowWithTorchAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithTorchAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithTorchAttachmentAndHeavyMech - 256).setIconIndex(3 + 64 + 32).setItemName("ironCrossbowWithTorchAttachmentAndHeavyMech").setMaxStackSize(1);
		ironCrossbowWithPoisonAttachment = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithPoisonAttachment - 256).setIconIndex(4 + 64 + 32).setItemName("ironCrossbowWithPoisonAttachment").setMaxStackSize(1);
		ironCrossbowWithPoisonAttachmentAndLightMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithPoisonAttachmentAndLightMech - 256).setIconIndex(5 + 64 + 32).setItemName("ironCrossbowWithPoisonAttachmentAndLightMech").setMaxStackSize(1);
		ironCrossbowWithPoisonAttachmentAndMediumMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithPoisonAttachmentAndMediumMech - 256).setIconIndex(6 + 64 + 32).setItemName("ironCrossbowWithPoisonAttachmentAndMediumMech").setMaxStackSize(1);
		ironCrossbowWithPoisonAttachmentAndHeavyMech = (ItemIronCrossbow) new ItemIronCrossbow(ConfigManager.idItemIronCrossbowWithPoisonAttachmentAndHeavyMech - 256).setIconIndex(7 + 64 + 32).setItemName("ironCrossbowWithPoisonAttachmentAndHeavyMech").setMaxStackSize(1);
		
		goldCrossbowBase = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowBase - 256).setIconIndex(0).setItemName("goldCrossbow").setMaxStackSize(1);
		goldCrossbowWithBasicScope = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithBasicScope - 256).setIconIndex(1).setItemName("goldCrossbowWithBasicScope").setMaxStackSize(1);
		goldCrossbowWithLongScope = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLongScope - 256).setIconIndex(2).setItemName("goldCrossbowWithLongScope").setMaxStackSize(1);
		goldCrossbowWithBasicScopeAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithBasicScopeAndLightMech - 256).setIconIndex(3).setItemName("goldCrossbowWithBasicScopeAndLightMech").setMaxStackSize(1);
		goldCrossbowWithLongScopeAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLongScopeAndLightMech - 256).setIconIndex(4).setItemName("goldCrossbowWithLongScopeAndLightMech").setMaxStackSize(1);
		goldCrossbowWithBasicScopeAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithBasicScopeAndMediumMech - 256).setIconIndex(5).setItemName("goldCrossbowWithBasicScopeAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithLongScopeAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLongScopeAndMediumMech - 256).setIconIndex(6).setItemName("goldCrossbowWithLongScopeAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithBasicScopeAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithBasicScopeAndHeavyMech - 256).setIconIndex(7).setItemName("goldCrossbowWithBasicScopeAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithLongScopeAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLongScopeAndHeavyMech - 256).setIconIndex(8).setItemName("goldCrossbowWithLongScopeAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLightMech - 256).setIconIndex(9).setItemName("goldCrossbowWithLightMech").setMaxStackSize(1);
		goldCrossbowWithMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithMediumMech - 256).setIconIndex(10).setItemName("goldCrossbowWithMediumMech").setMaxStackSize(1);
		goldCrossbowWithHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithHeavyMech - 256).setIconIndex(11).setItemName("goldCrossbowWithHeavyMech").setMaxStackSize(1);
		goldCrossbowWithExplosiveAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithExplosiveAttachment - 256).setIconIndex(12).setItemName("goldCrossbowWithExplosiveAttachment").setMaxStackSize(1);
		goldCrossbowWithExplosiveAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithExplosiveAttachmentAndLightMech - 256).setIconIndex(13).setItemName("goldCrossbowWithExplosiveAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithExplosiveAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithExplosiveAttachmentAndMediumMech - 256).setIconIndex(14).setItemName("goldCrossbowWithExplosiveAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithExplosiveAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithExplosiveAttachmentAndHeavyMech - 256).setIconIndex(15).setItemName("goldCrossbowWithExplosiveAttachmentAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithFlameAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithFireAttachment - 256).setIconIndex(0 + 32 + 16).setItemName("goldCrossbowWithFireAttachment").setMaxStackSize(1);
		goldCrossbowWithFlameAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithFireAttachmentAndLightMech - 256).setIconIndex(1 + 32 + 16).setItemName("goldCrossbowWithFireAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithFlameAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithFireAttachmentAndMediumMech - 256).setIconIndex(2 + 32 + 16).setItemName("goldCrossbowWithFireAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithFlameAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithFireAttachmentAndHeavyMech - 256).setIconIndex(3 + 32 + 16).setItemName("goldCrossbowWithFireAttachmentAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithLavaAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLavaAttachment - 256).setIconIndex(4 + 32 + 16).setItemName("goldCrossbowWithLavaAttachment").setMaxStackSize(1);
		goldCrossbowWithLavaAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLavaAttachmentAndLightMech - 256).setIconIndex(5 + 32 + 16).setItemName("goldCrossbowWithLavaAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithLavaAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLavaAttachmentAndMediumMech - 256).setIconIndex(6 + 32 + 16).setItemName("goldCrossbowWithLavaAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithLavaAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLavaAttachmentAndHeavyMech - 256).setIconIndex(7 + 32 + 16).setItemName("goldCrossbowWithLavaAttachmentAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithIceAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithIceAttachment - 256).setIconIndex(8 + 32 + 16).setItemName("goldCrossbowWithIceAttachment").setMaxStackSize(1);
		goldCrossbowWithIceAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithIceAttachmentAndLightMech - 256).setIconIndex(9 + 32 + 16).setItemName("goldCrossbowWithIceAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithIceAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithIceAttachmentAndMediumMech - 256).setIconIndex(10 + 32 + 16).setItemName("goldCrossbowWithIceAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithIceAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithIceAttachmentAndHeavyMech - 256).setIconIndex(11 + 32 + 16).setItemName("goldCrossbowWithIceAttachmentAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithLightningAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLightningAttachment - 256).setIconIndex(12 + 32 + 16).setItemName("goldCrossbowWithLightningAttachment").setMaxStackSize(1);
		goldCrossbowWithLightningAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLightningAttachmentAndLightMech - 256).setIconIndex(13 + 32 + 16).setItemName("goldCrossbowWithLightningAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithLightningAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLightningAttachmentAndMediumMech - 256).setIconIndex(14 + 32 + 16).setItemName("goldCrossbowWithLightningAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithLightningAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithLightningAttachmentAndHeavyMech - 256).setIconIndex(15 + 32 + 16).setItemName("goldCrossbowWithLightningAttachmentAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithTorchAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithTorchAttachment - 256).setIconIndex(0 + 64 + 32).setItemName("goldCrossbowWithTorchAttachment").setMaxStackSize(1);
		goldCrossbowWithTorchAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithTorchAttachmentAndLightMech - 256).setIconIndex(1 + 64 + 32).setItemName("goldCrossbowWithTorchAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithTorchAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithTorchAttachmentAndMediumMech - 256).setIconIndex(2 + 64 + 32).setItemName("goldCrossbowWithTorchAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithTorchAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithTorchAttachmentAndHeavyMech - 256).setIconIndex(3 + 64 + 32).setItemName("goldCrossbowWithTorchAttachmentAndHeavyMech").setMaxStackSize(1);
		goldCrossbowWithPoisonAttachment = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithPoisonAttachment - 256).setIconIndex(4 + 64 + 32).setItemName("goldCrossbowWithPoisonAttachment").setMaxStackSize(1);
		goldCrossbowWithPoisonAttachmentAndLightMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithPoisonAttachmentAndLightMech - 256).setIconIndex(5 + 64 + 32).setItemName("goldCrossbowWithPoisonAttachmentAndLightMech").setMaxStackSize(1);
		goldCrossbowWithPoisonAttachmentAndMediumMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithPoisonAttachmentAndMediumMech - 256).setIconIndex(6 + 64 + 32).setItemName("goldCrossbowWithPoisonAttachmentAndMediumMech").setMaxStackSize(1);
		goldCrossbowWithPoisonAttachmentAndHeavyMech = (ItemGoldCrossbow) new ItemGoldCrossbow(ConfigManager.idItemGoldCrossbowWithPoisonAttachmentAndHeavyMech - 256).setIconIndex(7 + 64 + 32).setItemName("goldCrossbowWithPoisonAttachmentAndHeavyMech").setMaxStackSize(1);
		
		diamondCrossbowBase = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowBase - 256).setIconIndex(0).setItemName("diamondCrossbow").setMaxStackSize(1);
		diamondCrossbowWithBasicScope = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithBasicScope - 256).setIconIndex(1).setItemName("diamondCrossbowWithBasicScope").setMaxStackSize(1);
		diamondCrossbowWithLongScope = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLongScope - 256).setIconIndex(2).setItemName("diamondCrossbowWithLongScope").setMaxStackSize(1);
		diamondCrossbowWithBasicScopeAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithBasicScopeAndLightMech - 256).setIconIndex(3).setItemName("diamondCrossbowWithBasicScopeAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithLongScopeAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLongScopeAndLightMech - 256).setIconIndex(4).setItemName("diamondCrossbowWithLongScopeAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithBasicScopeAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithBasicScopeAndMediumMech - 256).setIconIndex(5).setItemName("diamondCrossbowWithBasicScopeAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithLongScopeAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLongScopeAndMediumMech - 256).setIconIndex(6).setItemName("diamondCrossbowWithLongScopeAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithBasicScopeAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithBasicScopeAndHeavyMech - 256).setIconIndex(7).setItemName("diamondCrossbowWithBasicScopeAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithLongScopeAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLongScopeAndHeavyMech - 256).setIconIndex(8).setItemName("diamondCrossbowWithLongScopeAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLightMech - 256).setIconIndex(9).setItemName("diamondCrossbowWithLightMech").setMaxStackSize(1);
		diamondCrossbowWithMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithMediumMech - 256).setIconIndex(10).setItemName("diamondCrossbowWithMediumMech").setMaxStackSize(1);
		diamondCrossbowWithHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithHeavyMech - 256).setIconIndex(11).setItemName("diamondCrossbowWithHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithExplosiveAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithExplosiveAttachment - 256).setIconIndex(12).setItemName("diamondCrossbowWithExplosiveAttachment").setMaxStackSize(1);
		diamondCrossbowWithExplosiveAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithExplosiveAttachmentAndLightMech - 256).setIconIndex(13).setItemName("diamondCrossbowWithExplosiveAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithExplosiveAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithExplosiveAttachmentAndMediumMech - 256).setIconIndex(14).setItemName("diamondCrossbowWithExplosiveAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithExplosiveAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithExplosiveAttachmentAndHeavyMech - 256).setIconIndex(15).setItemName("diamondCrossbowWithExplosiveAttachmentAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithFlameAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithFireAttachment - 256).setIconIndex(0 + 32 + 16).setItemName("diamondCrossbowWithFireAttachment").setMaxStackSize(1);
		diamondCrossbowWithFlameAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithFireAttachmentAndLightMech - 256).setIconIndex(1 + 32 + 16).setItemName("diamondCrossbowWithFireAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithFlameAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithFireAttachmentAndMediumMech - 256).setIconIndex(2 + 32 + 16).setItemName("diamondCrossbowWithFireAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithFlameAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithFireAttachmentAndHeavyMech - 256).setIconIndex(3 + 32 + 16).setItemName("diamondCrossbowWithFireAttachmentAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithLavaAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLavaAttachment - 256).setIconIndex(4 + 32 + 16).setItemName("diamondCrossbowWithLavaAttachment").setMaxStackSize(1);
		diamondCrossbowWithLavaAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLavaAttachmentAndLightMech - 256).setIconIndex(5 + 32 + 16).setItemName("diamondCrossbowWithLavaAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithLavaAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLavaAttachmentAndMediumMech - 256).setIconIndex(6 + 32 + 16).setItemName("diamondCrossbowWithLavaAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithLavaAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLavaAttachmentAndHeavyMech - 256).setIconIndex(7 + 32 + 16).setItemName("diamondCrossbowWithLavaAttachmentAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithIceAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithIceAttachment - 256).setIconIndex(8 + 32 + 16).setItemName("diamondCrossbowWithIceAttachment").setMaxStackSize(1);
		diamondCrossbowWithIceAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithIceAttachmentAndLightMech - 256).setIconIndex(9 + 32 + 16).setItemName("diamondCrossbowWithIceAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithIceAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithIceAttachmentAndMediumMech - 256).setIconIndex(10 + 32 + 16).setItemName("diamondCrossbowWithIceAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithIceAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithIceAttachmentAndHeavyMech - 256).setIconIndex(11 + 32 + 16).setItemName("diamondCrossbowWithIceAttachmentAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithLightningAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLightningAttachment - 256).setIconIndex(12 + 32 + 16).setItemName("diamondCrossbowWithLightningAttachment").setMaxStackSize(1);
		diamondCrossbowWithLightningAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLightningAttachmentAndLightMech - 256).setIconIndex(13 + 32 + 16).setItemName("diamondCrossbowWithLightningAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithLightningAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLightningAttachmentAndMediumMech - 256).setIconIndex(14 + 32 + 16).setItemName("diamondCrossbowWithLightningAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithLightningAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithLightningAttachmentAndHeavyMech - 256).setIconIndex(15 + 32 + 16).setItemName("diamondCrossbowWithLightningAttachmentAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithTorchAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithTorchAttachment - 256).setIconIndex(0 + 64 + 32).setItemName("diamondCrossbowWithTorchAttachment").setMaxStackSize(1);
		diamondCrossbowWithTorchAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithTorchAttachmentAndLightMech - 256).setIconIndex(1 + 64 + 32).setItemName("diamondCrossbowWithTorchAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithTorchAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithTorchAttachmentAndMediumMech - 256).setIconIndex(2 + 64 + 32).setItemName("diamondCrossbowWithTorchAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithTorchAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithTorchAttachmentAndHeavyMech - 256).setIconIndex(3 + 64 + 32).setItemName("diamondCrossbowWithTorchAttachmentAndHeavyMech").setMaxStackSize(1);
		diamondCrossbowWithPoisonAttachment = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithPoisonAttachment - 256).setIconIndex(4 + 64 + 32).setItemName("diamondCrossbowWithPoisonAttachment").setMaxStackSize(1);
		diamondCrossbowWithPoisonAttachmentAndLightMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithPoisonAttachmentAndLightMech - 256).setIconIndex(5 + 64 + 32).setItemName("diamondCrossbowWithPoisonAttachmentAndLightMech").setMaxStackSize(1);
		diamondCrossbowWithPoisonAttachmentAndMediumMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithPoisonAttachmentAndMediumMech - 256).setIconIndex(6 + 64 + 32).setItemName("diamondCrossbowWithPoisonAttachmentAndMediumMech").setMaxStackSize(1);
		diamondCrossbowWithPoisonAttachmentAndHeavyMech = (ItemDiamondCrossbow) new ItemDiamondCrossbow(ConfigManager.idItemDiamondCrossbowWithPoisonAttachmentAndHeavyMech - 256).setIconIndex(7 + 64 + 32).setItemName("diamondCrossbowWithPoisonAttachmentAndHeavyMech").setMaxStackSize(1);

		woodBolt = (ItemCBMod) new ItemCBMod(ConfigManager.idItemWoodBolt - 256).setIconIndex(12).setItemName("woodenBolt");
		stoneBolt = (ItemCBMod) new ItemCBMod(ConfigManager.idItemStoneBolt - 256).setIconIndex(14).setItemName("stoneBolt");
		ironBolt = (ItemCBMod) new ItemCBMod(ConfigManager.idItemIronBolt - 256).setIconIndex(16).setItemName("ironBolt");
		goldBolt = (ItemCBMod) new ItemCBMod(ConfigManager.idItemGoldBolt - 256).setIconIndex(18).setItemName("goldBolt");
		diamondBolt = (ItemCBMod) new ItemCBMod(ConfigManager.idItemDiamondBolt - 256).setIconIndex(20).setItemName("diamondBolt");
		
		woodLimb = (ItemCBMod) new ItemCBMod(ConfigManager.idItemWoodLimb - 256).setIconIndex(13).setItemName("woodenLimb");
		stoneLimb = (ItemCBMod) new ItemCBMod(ConfigManager.idItemStoneLimb - 256).setIconIndex(15).setItemName("stoneLimb");
		ironLimb = (ItemCBMod) new ItemCBMod(ConfigManager.idItemIronLimb - 256).setIconIndex(17).setItemName("ironLimb");
		goldLimb = (ItemCBMod) new ItemCBMod(ConfigManager.idItemGoldLimb - 256).setIconIndex(19).setItemName("goldLimb");
		diamondLimb = (ItemCBMod) new ItemCBMod(ConfigManager.idItemDiamondLimb - 256).setIconIndex(21).setItemName("diamondLimb");
		
		mechanismSemiAuto = (ItemCBMod) new ItemCBMod(ConfigManager.idItemSemiAutoMechanism - 256).setIconIndex(3).setItemName("semiAutoMechanism");
		mechanismLightAuto = (ItemCBMod) new ItemCBMod(ConfigManager.idItemLightAutoMechanism - 256).setIconIndex(4).setItemName("lightAutoMechanism");
		mechanismMediumAuto = (ItemCBMod) new ItemCBMod(ConfigManager.idItemMediumAutoMechanism - 256).setIconIndex(5).setItemName("medAutoMechanism");
		mechanismHeavyAuto = (ItemCBMod) new ItemCBMod(ConfigManager.idItemHeavyAutoMechanism - 256).setIconIndex(6).setItemName("heavyAutoMechanism");
		attachmentShortScope = (ItemCBMod) new ItemCBMod(ConfigManager.idItemBasicScope - 256).setIconIndex(7).setItemName("attachmentShortScope");
		attachmentLongScope = (ItemCBMod) new ItemCBMod(ConfigManager.idItemLongRangeScope - 256).setIconIndex(8).setItemName("attachmentLongScope");
		attachmentFire = (ItemCBMod) new ItemCBMod(ConfigManager.idItemFlameAttachment - 256).setIconIndex(10).setItemName("attachmentFire");
		attachmentExplosive = (ItemCBMod) new ItemCBMod(ConfigManager.idItemExplosiveAttachment - 256).setIconIndex(9).setItemName("attachmentExplosive");
		attachmentLava = (ItemCBMod) new ItemCBMod(ConfigManager.idItemLavaAttachment - 256).setIconIndex(11).setItemName("attachmentLava");
		attachmentIce = (ItemCBMod) new ItemCBMod(ConfigManager.idItemIceAttachment - 256).setIconIndex(22).setItemName("attachmentIce");
		attachmentLightning = (ItemCBMod) new ItemCBMod(ConfigManager.idItemLightningAttachment - 256).setIconIndex(23).setItemName("attachmentLightning");
		attachmentTorch = (ItemCBMod) new ItemCBMod(ConfigManager.idItemTorchAttachment - 256).setIconIndex(24).setItemName("attachmentTorch");
		attachmentPoison = (ItemCBMod) new ItemCBMod(ConfigManager.idItemPoisonAttachment - 256).setIconIndex(25).setItemName("attachmentPoison");
	}
	
	public static void addNames()
	{
        LanguageRegistry.instance().addNameForObject(woodenCrossbowBase, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithBasicScope, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLongScope, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithBasicScopeAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLongScopeAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithBasicScopeAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLongScopeAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithBasicScopeAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLongScopeAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithExplosiveAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithExplosiveAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithExplosiveAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithExplosiveAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithFlameAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithFlameAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithFlameAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithFlameAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLavaAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLavaAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLavaAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLavaAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithIceAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithIceAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithIceAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithIceAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLightningAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLightningAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLightningAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithLightningAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithTorchAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithTorchAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithTorchAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithTorchAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithPoisonAttachment, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithPoisonAttachmentAndLightMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithPoisonAttachmentAndMediumMech, "en_US", "Wooden Crossbow");
        LanguageRegistry.instance().addNameForObject(woodenCrossbowWithPoisonAttachmentAndHeavyMech, "en_US", "Wooden Crossbow");

        LanguageRegistry.instance().addNameForObject(stoneCrossbowBase, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithBasicScope, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLongScope, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithBasicScopeAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLongScopeAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithBasicScopeAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLongScopeAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithBasicScopeAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLongScopeAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithExplosiveAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithExplosiveAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithExplosiveAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithExplosiveAttachmentAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithFlameAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithFlameAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithFlameAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithFlameAttachmentAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLavaAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLavaAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLavaAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLavaAttachmentAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithIceAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithIceAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithIceAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithIceAttachmentAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLightningAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLightningAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLightningAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithLightningAttachmentAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithTorchAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithTorchAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithTorchAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithTorchAttachmentAndHeavyMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithPoisonAttachment, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithPoisonAttachmentAndLightMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithPoisonAttachmentAndMediumMech, "en_US", "Stone Crossbow");
        LanguageRegistry.instance().addNameForObject(stoneCrossbowWithPoisonAttachmentAndHeavyMech, "en_US", "Stone Crossbow");

        LanguageRegistry.instance().addNameForObject(ironCrossbowBase, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithBasicScope, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLongScope, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithBasicScopeAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLongScopeAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithBasicScopeAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLongScopeAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithBasicScopeAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLongScopeAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithExplosiveAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithExplosiveAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithExplosiveAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithExplosiveAttachmentAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithFlameAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithFlameAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithFlameAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithFlameAttachmentAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLavaAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLavaAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLavaAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLavaAttachmentAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithIceAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithIceAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithIceAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithIceAttachmentAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLightningAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLightningAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLightningAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithLightningAttachmentAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithTorchAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithTorchAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithTorchAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithTorchAttachmentAndHeavyMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithPoisonAttachment, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithPoisonAttachmentAndLightMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithPoisonAttachmentAndMediumMech, "en_US", "Iron Crossbow");
        LanguageRegistry.instance().addNameForObject(ironCrossbowWithPoisonAttachmentAndHeavyMech, "en_US", "Iron Crossbow");

        LanguageRegistry.instance().addNameForObject(goldCrossbowBase, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithBasicScope, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLongScope, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithBasicScopeAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLongScopeAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithBasicScopeAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLongScopeAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithBasicScopeAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLongScopeAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithExplosiveAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithExplosiveAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithExplosiveAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithExplosiveAttachmentAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithFlameAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithFlameAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithFlameAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithFlameAttachmentAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLavaAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLavaAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLavaAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLavaAttachmentAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithIceAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithIceAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithIceAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithIceAttachmentAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLightningAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLightningAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLightningAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithLightningAttachmentAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithTorchAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithTorchAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithTorchAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithTorchAttachmentAndHeavyMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithPoisonAttachment, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithPoisonAttachmentAndLightMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithPoisonAttachmentAndMediumMech, "en_US", "Gold Crossbow");
        LanguageRegistry.instance().addNameForObject(goldCrossbowWithPoisonAttachmentAndHeavyMech, "en_US", "Gold Crossbow");

        LanguageRegistry.instance().addNameForObject(diamondCrossbowBase, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithBasicScope, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLongScope, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithBasicScopeAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLongScopeAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithBasicScopeAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLongScopeAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithBasicScopeAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLongScopeAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithExplosiveAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithExplosiveAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithExplosiveAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithExplosiveAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithFlameAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithFlameAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithFlameAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithFlameAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLavaAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLavaAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLavaAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLavaAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithIceAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithIceAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithIceAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithIceAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLightningAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLightningAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLightningAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithLightningAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithTorchAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithTorchAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithTorchAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithTorchAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithPoisonAttachment, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithPoisonAttachmentAndLightMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithPoisonAttachmentAndMediumMech, "en_US", "Diamond Crossbow");
        LanguageRegistry.instance().addNameForObject(diamondCrossbowWithPoisonAttachmentAndHeavyMech, "en_US", "Diamond Crossbow");

        LanguageRegistry.instance().addNameForObject(woodBolt, "en_US", "Wood Bolt");
        LanguageRegistry.instance().addNameForObject(stoneBolt, "en_US", "Stone Bolt");
        LanguageRegistry.instance().addNameForObject(ironBolt, "en_US", "Iron Bolt");
        LanguageRegistry.instance().addNameForObject(goldBolt, "en_US", "Gold Bolt");
        LanguageRegistry.instance().addNameForObject(diamondBolt, "en_US", "Diamond Bolt");
        
        LanguageRegistry.instance().addNameForObject(woodLimb, "en_US", "Wood Limb");
        LanguageRegistry.instance().addNameForObject(stoneLimb, "en_US", "Stone Limb");
        LanguageRegistry.instance().addNameForObject(ironLimb, "en_US", "Iron Limb");
        LanguageRegistry.instance().addNameForObject(goldLimb, "en_US", "Gold Limb");
        LanguageRegistry.instance().addNameForObject(diamondLimb, "en_US", "Diamond Limb");
		
		LanguageRegistry.instance().addNameForObject(mechanismSemiAuto, "en_US",  "Basic Crossbow Mechanism");
		LanguageRegistry.instance().addNameForObject(mechanismLightAuto, "en_US",  "Light Automatic Crossbow Mechanism");
		LanguageRegistry.instance().addNameForObject(mechanismMediumAuto, "en_US",  "Medium Automatic Crossbow Mechanism");
		LanguageRegistry.instance().addNameForObject(mechanismHeavyAuto, "en_US",  "Heavy Automatic Crossbow Mechanism");
		
		LanguageRegistry.instance().addNameForObject(attachmentShortScope, "en_US",  "Basic Crossbow Scope");
		LanguageRegistry.instance().addNameForObject(attachmentLongScope, "en_US",  "Long-Range Crossbow Scope");
		LanguageRegistry.instance().addNameForObject(attachmentExplosive, "en_US",  "Explosive Crossbow Attachment");
		LanguageRegistry.instance().addNameForObject(attachmentFire, "en_US",  "Flame Crossbow Attachment");
		LanguageRegistry.instance().addNameForObject(attachmentLava, "en_US",  "Lava Crossbow Attachment");
		LanguageRegistry.instance().addNameForObject(attachmentIce, "en_US",  "Frost Crossbow Attachment");
		LanguageRegistry.instance().addNameForObject(attachmentLightning, "en_US",  "Lightning Crossbow Attachment");
		LanguageRegistry.instance().addNameForObject(attachmentTorch, "en_US",  "Torch Crossbow Attachment");
		LanguageRegistry.instance().addNameForObject(attachmentPoison, "en_US",  "Poison Crossbow Attachment");
		
		LanguageRegistry.instance().addNameForObject(crossbowBench, "en_US", "Crossbow Crafting Bench");
	}
}
